### ISSUE TITLE
Sorry to bother you. I'm a fresh learner of this filed. I could't understand the meaning of the data afer searching in Internet, could you please explain it when you are free. Thank you so much for your generosity.

### ISSUE THREAD

**Issue by gufugui** [rodrigo-brito/facility-location-gurobi#1]
Sorry to bother you. I'm a fresh learner of this filed. I could't understand the meaning of the data afer searching in Internet, could you please explain it when you are free. Thank you so much for your generosity.

**Comment by rodrigo-brito** [comment]
Hi @gujiangyan,
The data file contains 5 input structures.
For example: https://github.com/rodrigo-brito/facility-location-gurobi/blob/master/data/ap10_2.txt
Contains a data for a networks with 10 nodes.

First value: number of nodes (N)
Second value: factor of discount for hubs connection (alpha)
Next N lines are the cost of hub installation in node k. `f_k` where `k = [1..10]` in this case

Finally, we have two matrix `NxN`:
- The first matrix contains the demand of flow between `i` and `j` = `W_ij`
- The second matrix contains the cost of transport an unit of flow between `i` and `j` = `C_ij`.

I read the input in this file: https://github.com/rodrigo-brito/facility-location-gurobi/blob/master/model/input.py

![image](https://user-images.githubusercontent.com/7620947/101842914-d6e49500-3b27-11eb-8eb5-0dbdcaacc4a1.png)

**Comment by gufugui** [comment]
Thank you so much for your detailed explanation, I've learned a lot from this project. Hope you have a good day~

**Comment by rodrigo-brito** [comment]
You're welcome
